# Generated by Django 4.2.13 on 2024-08-07 15:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogstory',
            name='story',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
