# Generated by Django 4.2.13 on 2024-08-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogstory',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
